; Configuración global de Gammastep
[general]
temp-day=6500
temp-night=3000

; Transición suave entre día y noche (0 = instantáneo, 1 = suave)
fade=1

; Método de ajuste obligatorio para Sway (Wayland)
location-provider=manual
adjustment-method=wayland

[manual]
lat=-12.04
lon=-77.03
